"""配置模块：自动生成 config.json + 参数校验 + 热重载"""
import json
import os

DEFAULT_CONFIG = {
    "RPC_URL": "http://127.0.0.1:6800/jsonrpc",
    "RPC_TOKEN": "",
    "CHECK_INTERVAL": 1,
    "WARMUP_SEC": 10,
    "PAUSE_WAIT_SEC": 1,
    "MIN_TRIGGER_SPEED": 200 * 1024,
    "FIT_WINDOW_SIZE": 8,
    "MAX_ADJUST_RATIO": 0.15,
    "DRIFT_DETECT_THRESHOLD": 0.2,
    "LOW_SPEED_TRIGGER_COUNT": 3,
    "SPEED_DROP_FILTER": 0.5,
    "PHASE_FACTOR_MIN": 0.9,
    "PHASE_FACTOR_MAX": 1.1,
    "PEAK_HISTORY_SIZE": 20,
    "PEAK_CAP_PERCENTILE": 0.95,
    "PREDICTIVE_TRIGGER_ENABLED": True,
    "PREDICTIVE_GAP_SEC": 1.5,
    "PREDICTIVE_SPEED_MARGIN": 0.15,
    "VOLATILITY_THRESHOLD": 0.15,
    "SECOND_ORDER_SENSITIVITY": 0.8,
    "USE_BAYESIAN_OPT": True,
    "BAYES_OPT_INIT_SAMPLES": 5,
    "BAYES_OPT_ACQ_FUNC": "ei_decay",
    "BAYES_OPT_CANDIDATES": 200,
    "OPT_THRESHOLD_RANGE": [0.3, 0.9],
    "OPT_WARMUP_RANGE": [5, 30],
    "EXPLORE_KAPPA_START": 1.0,
    "EXPLORE_KAPPA_MIN": 0.3,
    "USE_PATTERN_CLUSTER": True,
    "CLUSTER_K": 3,
    "CLUSTER_FEATURE_WINDOW": 20,
    "CLUSTER_UPDATE_FREQ": 10,
    "ENABLE_PERSISTENCE": True,
    "PERSIST_FILE": "ariaboost_state.json",
    "PERSIST_SAVE_INTERVAL": 5,
    "MAX_OBS_HISTORY": 200,
    "RPC_HEALTH_CHECK_INTERVAL": 30,
    "RPC_MAX_FAILURES": 3,
    "RPC_RECOVER_WAIT": 5,
    "SMOOTH_FACTOR": 0.3,
    "DISABLE_AFTER_PROGRESS": 0.95,
    "DISABLE_REMAINING_MB": 50,
    "LOG_LEVEL": "INFO",
    "SHOW_CHART": False,
    "CHART_UPDATE_INTERVAL": 5,
    "MAX_CHART_POINTS": 100,
    "THEME": "light",
    # 新增参数
    "TRIGGER_COUNT_RANGE": [1, 5],
    "PREDICT_MARGIN_RANGE": [0.05, 0.25],
    "DROP_FILTER_RANGE": [0.3, 0.8],
    "ANOMALY_DETECTION_ENABLED": True,
    "CIRCUIT_BREAKER_ENABLED": True,
    "USE_PATTERN_CLUSTER": True,
    "CLUSTER_K": 3,
}

CONFIG_FILE = "config.json"

def _validate(cfg):
    def get_safe(k, minv=None, maxv=None, is_int=False):
        val = cfg.get(k, DEFAULT_CONFIG[k])
        if minv is not None and val < minv:
            return DEFAULT_CONFIG[k]
        if maxv is not None and val > maxv:
            return DEFAULT_CONFIG[k]
        if is_int and not isinstance(val, int):
            return DEFAULT_CONFIG[k]
        return val

    cfg["CHECK_INTERVAL"] = get_safe("CHECK_INTERVAL", 0.1)
    cfg["CLUSTER_K"] = get_safe("CLUSTER_K", 1, None, True)
    cfg["BAYES_OPT_CANDIDATES"] = get_safe("BAYES_OPT_CANDIDATES", 10, None, True)
    cfg["MAX_OBS_HISTORY"] = get_safe("MAX_OBS_HISTORY", 10, None, True)

    if "OPT_THRESHOLD_RANGE" in cfg:
        cfg["OPT_THRESHOLD_RANGE"][0] = max(0.2, cfg["OPT_THRESHOLD_RANGE"][0])
        cfg["OPT_THRESHOLD_RANGE"][1] = min(0.95, cfg["OPT_THRESHOLD_RANGE"][1])
        if cfg["OPT_THRESHOLD_RANGE"][0] >= cfg["OPT_THRESHOLD_RANGE"][1]:
            cfg["OPT_THRESHOLD_RANGE"] = [0.3, 0.9]

    if "OPT_WARMUP_RANGE" in cfg:
        cfg["OPT_WARMUP_RANGE"][0] = max(3, cfg["OPT_WARMUP_RANGE"][0])
        cfg["OPT_WARMUP_RANGE"][1] = min(60, cfg["OPT_WARMUP_RANGE"][1])
        if cfg["OPT_WARMUP_RANGE"][0] >= cfg["OPT_WARMUP_RANGE"][1]:
            cfg["OPT_WARMUP_RANGE"] = [5, 30]

    if "TRIGGER_COUNT_RANGE" in cfg:
        cfg["TRIGGER_COUNT_RANGE"][0] = max(1, cfg["TRIGGER_COUNT_RANGE"][0])
        cfg["TRIGGER_COUNT_RANGE"][1] = min(5, cfg["TRIGGER_COUNT_RANGE"][1])
        if cfg["TRIGGER_COUNT_RANGE"][0] >= cfg["TRIGGER_COUNT_RANGE"][1]:
            cfg["TRIGGER_COUNT_RANGE"] = [1, 5]

    cfg["LOW_SPEED_TRIGGER_COUNT"] = max(2, cfg.get("LOW_SPEED_TRIGGER_COUNT", 3))
    cfg["DISABLE_REMAINING_MB"] = max(1, cfg.get("DISABLE_REMAINING_MB", 50))
    cfg["WARMUP_SEC"] = max(3, cfg.get("WARMUP_SEC", 10))

    return cfg

def load_config():
    if not os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "w", encoding="utf-8") as f:
                json.dump(DEFAULT_CONFIG, f, indent=4, ensure_ascii=False)
            print(f"已自动生成默认配置文件: {CONFIG_FILE}")
        except Exception as e:
            print(f"无法创建 {CONFIG_FILE}: {e}")
    config = DEFAULT_CONFIG.copy()
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                user_config = json.load(f)
            config.update(user_config)
            config = _validate(config)
        except Exception as e:
            print(f"配置文件加载失败: {e}")
    return config

def reload_config():
    global CONFIG, RPC_URL, RPC_TOKEN, CHECK_INTERVAL, WARMUP_SEC
    global PAUSE_WAIT_SEC, MIN_TRIGGER_SPEED, FIT_WINDOW_SIZE, MAX_ADJUST_RATIO
    global DRIFT_DETECT_THRESHOLD, LOW_SPEED_TRIGGER_COUNT, SPEED_DROP_FILTER
    global PHASE_FACTOR_MIN, PHASE_FACTOR_MAX, PEAK_HISTORY_SIZE, PEAK_CAP_PERCENTILE
    global PREDICTIVE_TRIGGER_ENABLED, PREDICTIVE_GAP_SEC, PREDICTIVE_SPEED_MARGIN
    global VOLATILITY_THRESHOLD, SECOND_ORDER_SENSITIVITY, USE_BAYESIAN_OPT
    global BAYES_OPT_INIT_SAMPLES, BAYES_OPT_ACQ_FUNC, BAYES_OPT_CANDIDATES
    global OPT_THRESHOLD_RANGE, OPT_WARMUP_RANGE, EXPLORE_KAPPA_START, EXPLORE_KAPPA_MIN
    global USE_PATTERN_CLUSTER, CLUSTER_K, CLUSTER_FEATURE_WINDOW, CLUSTER_UPDATE_FREQ
    global ENABLE_PERSISTENCE, PERSIST_FILE, PERSIST_SAVE_INTERVAL, MAX_OBS_HISTORY
    global RPC_HEALTH_CHECK_INTERVAL, RPC_MAX_FAILURES, RPC_RECOVER_WAIT, SMOOTH_FACTOR
    global DISABLE_AFTER_PROGRESS, DISABLE_REMAINING_MB, LOG_LEVEL, SHOW_CHART
    global CHART_UPDATE_INTERVAL, MAX_CHART_POINTS, THEME
    global TRIGGER_COUNT_RANGE, PREDICT_MARGIN_RANGE, DROP_FILTER_RANGE
    global ANOMALY_DETECTION_ENABLED, CIRCUIT_BREAKER_ENABLED

    CONFIG = load_config()
    RPC_URL = CONFIG["RPC_URL"]
    RPC_TOKEN = CONFIG["RPC_TOKEN"]
    CHECK_INTERVAL = CONFIG["CHECK_INTERVAL"]
    WARMUP_SEC = CONFIG["WARMUP_SEC"]
    PAUSE_WAIT_SEC = CONFIG["PAUSE_WAIT_SEC"]
    MIN_TRIGGER_SPEED = CONFIG["MIN_TRIGGER_SPEED"]
    FIT_WINDOW_SIZE = CONFIG["FIT_WINDOW_SIZE"]
    MAX_ADJUST_RATIO = CONFIG["MAX_ADJUST_RATIO"]
    DRIFT_DETECT_THRESHOLD = CONFIG["DRIFT_DETECT_THRESHOLD"]
    LOW_SPEED_TRIGGER_COUNT = CONFIG["LOW_SPEED_TRIGGER_COUNT"]
    SPEED_DROP_FILTER = CONFIG["SPEED_DROP_FILTER"]
    PHASE_FACTOR_MIN = CONFIG["PHASE_FACTOR_MIN"]
    PHASE_FACTOR_MAX = CONFIG["PHASE_FACTOR_MAX"]
    PEAK_HISTORY_SIZE = CONFIG["PEAK_HISTORY_SIZE"]
    PEAK_CAP_PERCENTILE = CONFIG["PEAK_CAP_PERCENTILE"]
    PREDICTIVE_TRIGGER_ENABLED = CONFIG["PREDICTIVE_TRIGGER_ENABLED"]
    PREDICTIVE_GAP_SEC = CONFIG["PREDICTIVE_GAP_SEC"]
    PREDICTIVE_SPEED_MARGIN = CONFIG["PREDICTIVE_SPEED_MARGIN"]
    VOLATILITY_THRESHOLD = CONFIG["VOLATILITY_THRESHOLD"]
    SECOND_ORDER_SENSITIVITY = CONFIG["SECOND_ORDER_SENSITIVITY"]
    USE_BAYESIAN_OPT = CONFIG["USE_BAYESIAN_OPT"]
    BAYES_OPT_INIT_SAMPLES = CONFIG["BAYES_OPT_INIT_SAMPLES"]
    BAYES_OPT_ACQ_FUNC = CONFIG["BAYES_OPT_ACQ_FUNC"]
    BAYES_OPT_CANDIDATES = CONFIG["BAYES_OPT_CANDIDATES"]
    OPT_THRESHOLD_RANGE = tuple(CONFIG["OPT_THRESHOLD_RANGE"])
    OPT_WARMUP_RANGE = tuple(CONFIG["OPT_WARMUP_RANGE"])
    EXPLORE_KAPPA_START = CONFIG["EXPLORE_KAPPA_START"]
    EXPLORE_KAPPA_MIN = CONFIG["EXPLORE_KAPPA_MIN"]
    USE_PATTERN_CLUSTER = CONFIG["USE_PATTERN_CLUSTER"]
    CLUSTER_K = CONFIG["CLUSTER_K"]
    CLUSTER_FEATURE_WINDOW = CONFIG["CLUSTER_FEATURE_WINDOW"]
    CLUSTER_UPDATE_FREQ = CONFIG["CLUSTER_UPDATE_FREQ"]
    ENABLE_PERSISTENCE = CONFIG["ENABLE_PERSISTENCE"]
    PERSIST_FILE = CONFIG["PERSIST_FILE"]
    PERSIST_SAVE_INTERVAL = CONFIG["PERSIST_SAVE_INTERVAL"]
    MAX_OBS_HISTORY = CONFIG["MAX_OBS_HISTORY"]
    RPC_HEALTH_CHECK_INTERVAL = CONFIG["RPC_HEALTH_CHECK_INTERVAL"]
    RPC_MAX_FAILURES = CONFIG["RPC_MAX_FAILURES"]
    RPC_RECOVER_WAIT = CONFIG["RPC_RECOVER_WAIT"]
    SMOOTH_FACTOR = CONFIG["SMOOTH_FACTOR"]
    DISABLE_AFTER_PROGRESS = CONFIG["DISABLE_AFTER_PROGRESS"]
    DISABLE_REMAINING_MB = CONFIG["DISABLE_REMAINING_MB"]
    LOG_LEVEL = CONFIG["LOG_LEVEL"]
    SHOW_CHART = CONFIG["SHOW_CHART"]
    CHART_UPDATE_INTERVAL = CONFIG["CHART_UPDATE_INTERVAL"]
    MAX_CHART_POINTS = CONFIG["MAX_CHART_POINTS"]
    THEME = CONFIG.get("THEME", "light")
    TRIGGER_COUNT_RANGE = tuple(CONFIG["TRIGGER_COUNT_RANGE"])
    PREDICT_MARGIN_RANGE = tuple(CONFIG["PREDICT_MARGIN_RANGE"])
    DROP_FILTER_RANGE = tuple(CONFIG["DROP_FILTER_RANGE"])
    ANOMALY_DETECTION_ENABLED = CONFIG["ANOMALY_DETECTION_ENABLED"]
    CIRCUIT_BREAKER_ENABLED = CONFIG["CIRCUIT_BREAKER_ENABLED"]

# 加载配置
CONFIG = load_config()
reload_config()